import { Novel, Chapter } from './types';

// Working sample audio URLs for realistic web audio playback
const SAMPLE_AUDIO_URLS = [
  'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
  'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
  'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
  'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
  'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
];

export const MOCK_CHAPTERS: Record<string, Chapter[]> = {
  'n1': [
    {
      id: 'c1-1',
      novelId: 'n1',
      chapterNumber: 1,
      title: 'ตอนที่ 1: การตื่นขึ้นของจักรพรรดิมังกร',
      audioUrl: SAMPLE_AUDIO_URLS[0],
      duration: 372, // 6:12
      releasedAt: '2026-07-01',
      views: 15420,
    },
    {
      id: 'c1-2',
      novelId: 'n1',
      chapterNumber: 2,
      title: 'ตอนที่ 2: ความลับแห่งหุบเขาหมอกควัน',
      audioUrl: SAMPLE_AUDIO_URLS[1],
      duration: 425, // 7:05
      releasedAt: '2026-07-03',
      views: 12890,
    },
    {
      id: 'c1-3',
      novelId: 'n1',
      chapterNumber: 3,
      title: 'ตอนที่ 3: กระบี่หยกไร้พ่าย',
      audioUrl: SAMPLE_AUDIO_URLS[2],
      duration: 510, // 8:30
      releasedAt: '2026-07-07',
      views: 11200,
    },
    {
      id: 'c1-4',
      novelId: 'n1',
      chapterNumber: 4,
      title: 'ตอนที่ 4: การประลองสำนักเทวะ',
      audioUrl: SAMPLE_AUDIO_URLS[3],
      duration: 480, // 8:00
      releasedAt: '2026-07-12',
      views: 9800,
    },
    {
      id: 'c1-5',
      novelId: 'n1',
      chapterNumber: 5,
      title: 'ตอนที่ 5: พลังที่แทรกซ่อนในสายเลือด',
      audioUrl: SAMPLE_AUDIO_URLS[4],
      duration: 440, // 7:20
      releasedAt: '2026-07-18',
      views: 8950,
    },
  ],
  'n2': [
    {
      id: 'c2-1',
      novelId: 'n2',
      chapterNumber: 1,
      title: 'ตอนที่ 1: หญิงสาวจากอนาคตและระบบเทพแพทย์',
      audioUrl: SAMPLE_AUDIO_URLS[1],
      duration: 410,
      releasedAt: '2026-07-10',
      views: 22100,
    },
    {
      id: 'c2-2',
      novelId: 'n2',
      chapterNumber: 2,
      title: 'ตอนที่ 2: การรักษาอ๋องสามในคืนพระจันทร์ดับ',
      audioUrl: SAMPLE_AUDIO_URLS[2],
      duration: 490,
      releasedAt: '2026-07-14',
      views: 18900,
    },
    {
      id: 'c2-3',
      novelId: 'n2',
      chapterNumber: 3,
      title: 'ตอนที่ 3: เงื่อนไขสัญญาแต่งงานพันล้าน',
      audioUrl: SAMPLE_AUDIO_URLS[3],
      duration: 380,
      releasedAt: '2026-07-20',
      views: 16500,
    },
  ],
  'n3': [
    {
      id: 'c3-1',
      novelId: 'n3',
      chapterNumber: 1,
      title: 'ตอนที่ 1: คดีรอยยิ้มปริศนาในคฤหาสน์เก่า',
      audioUrl: SAMPLE_AUDIO_URLS[3],
      duration: 520,
      releasedAt: '2026-07-15',
      views: 8400,
    },
    {
      id: 'c3-2',
      novelId: 'n3',
      chapterNumber: 2,
      title: 'ตอนที่ 2: เงาในสายฝนและคำขู่เลือด',
      audioUrl: SAMPLE_AUDIO_URLS[4],
      duration: 465,
      releasedAt: '2026-07-22',
      views: 7100,
    },
  ],
  'n4': [
    {
      id: 'c4-1',
      novelId: 'n4',
      chapterNumber: 1,
      title: 'ตอนที่ 1: จุติใหม่ในเกมออนไลน์ระดับตำนาน',
      audioUrl: SAMPLE_AUDIO_URLS[0],
      duration: 395,
      releasedAt: '2026-07-05',
      views: 19800,
    },
    {
      id: 'c4-2',
      novelId: 'n4',
      chapterNumber: 2,
      title: 'ตอนที่ 2: ไอเทมระดับพระเจ้าชิ้นแรก',
      audioUrl: SAMPLE_AUDIO_URLS[1],
      duration: 430,
      releasedAt: '2026-07-09',
      views: 17200,
    },
  ],
};

export const MOCK_NOVELS: Novel[] = [
  {
    id: 'n1',
    title: 'จักรพรรดิมังกรโบราณคืนสู่นคร',
    slug: 'ancient-dragon-emperor',
    coverUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200&q=80',
    author: 'เทียนหลง (Tian Long)',
    translator: 'แอดมินบอน (MaFangNiyai Official)',
    synopsis: 'หลังจากจำศีลยาวนานนับพันปี ในที่สุดจอมจักรพรรดิมังกรผู้เกรียงไกรก็ได้ลืมตาขึ้นอีกครั้งในยุคปัจจุบัน ท่ามกลางเมืองหลวงที่คลาคล่ำไปด้วยผู้ฝึกตนยุคใหม่และเทคโนโลยีลึกลับ เขาต้องทวงคืนความยิ่งใหญ่และปกป้องตระกูลที่ถูกกดขี่!',
    category: 'กำลังภายใน',
    tags: ['เทพสงคราม', 'พระเอกเก่ง', 'แก้แค้น', 'เกิดใหม่'],
    rating: 4.9,
    ratingCount: 1420,
    viewCount: 58260,
    favoriteCount: 8940,
    isFeatured: true,
    isCompleted: false,
    totalChapters: 5,
    createdAt: '2026-07-01',
    updatedAt: '2026-07-18',
    chapters: MOCK_CHAPTERS['n1'],
  },
  {
    id: 'n2',
    title: 'ยอดแพทย์หญิงข้ามมิติกับระบบอัจฉริยะ',
    slug: 'genius-doctor-transmigration',
    coverUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=1200&q=80',
    author: 'หลินเสวี่ย (Lin Xue)',
    translator: 'ทีมงานมาฟังนิยาย',
    synopsis: 'ศัลยแพทย์หญิงระดับโลกประสบอุบัติเหตุย้อนเวลาไปอยู่ในร่างของคุณหนูไร้ค่าแห่งวังหลวงยุคโบราณ พร้อมกับระบบการแพทย์สุดล้ำอนาคต! เธอจึงใช้ความรู้รักษาผู้คนและเอาชนะศัตรูในวังหลวงที่จ้องเล่นงานเธอ',
    category: 'รักโรแมนติก / ย้อนยุค',
    tags: ['ข้ามมิติ', 'แพทย์หญิง', 'ชิงไหวชิงพริบ', 'วังหลวง'],
    rating: 4.8,
    ratingCount: 1980,
    viewCount: 57500,
    favoriteCount: 12400,
    isFeatured: true,
    isCompleted: false,
    totalChapters: 3,
    createdAt: '2026-07-10',
    updatedAt: '2026-07-20',
    chapters: MOCK_CHAPTERS['n2'],
  },
  {
    id: 'n3',
    title: 'รหัสลับคดีศพในคฤหาสน์เที่ยงคืน',
    slug: 'midnight-mansion-murder',
    coverUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&q=80',
    author: 'Blackwood',
    translator: 'แอดมินบอน (MaFangNiyai Official)',
    synopsis: 'นักสืบเอกชนได้รับคำท้าทายจากฆาตกรปริศนาในคืนฝนตกชุก คดีสังหารปิยวรรณในห้องปิดตายกลายเป็นปริศนาที่ไม่มีใครแก้ได้ มีเพียงเสียงบันทึกปริศนาที่เหลือทิ้งไว้ในเครื่องเล่นแผ่นเสียงเท่านั้น!',
    category: 'สืบสวนสอบสวน / สยองขวัญ',
    tags: ['ห้องปิดตาย', 'หักมุม', 'นักสืบ', 'ปริศนา'],
    rating: 4.7,
    ratingCount: 650,
    viewCount: 15500,
    favoriteCount: 3200,
    isFeatured: false,
    isCompleted: true,
    totalChapters: 2,
    createdAt: '2026-07-15',
    updatedAt: '2026-07-22',
    chapters: MOCK_CHAPTERS['n3'],
  },
  {
    id: 'n4',
    title: 'จุติใหม่ใน MMO โลกเสมือนกับบั๊กอินฟินิตี้',
    slug: 'reborn-mmo-infinity-bug',
    coverUrl: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=600&q=80',
    author: 'CyberKnight',
    translator: 'ทีมงานมาฟังนิยาย',
    synopsis: 'เมื่อโปรแกรมเมอร์หนุ่มตกงานย้อนเวลากลับมาเมื่อ 10 ปีก่อน ในวันที่เกม VRMMO ระดับโลกเปิดตัวเป็นวันแรก เขาใช้ความทรงจำล่วงหน้าค้นหาบั๊กคูณทวีคูณสกิล จนกลายเป็นผู้เล่นอันดับหนึ่งของโลก!',
    category: 'แฟนตาซี / เกมออนไลน์',
    tags: ['เกมออนไลน์', 'เทพตั้งแต่ต้น', 'เกิดใหม่', 'ระบบ'],
    rating: 4.85,
    ratingCount: 1100,
    viewCount: 37000,
    favoriteCount: 7800,
    isFeatured: true,
    isCompleted: false,
    totalChapters: 2,
    createdAt: '2026-07-05',
    updatedAt: '2026-07-09',
    chapters: MOCK_CHAPTERS['n4'],
  },
];

export const CATEGORIES = [
  'ทั้งหมด',
  'กำลังภายใน',
  'รักโรแมนติก / ย้อนยุค',
  'แฟนตาซี / เกมออนไลน์',
  'สืบสวนสอบสวน / สยองขวัญ',
  'ระบบ / เกิดใหม่',
];
